-- AlterTable
ALTER TABLE `material_requests` MODIFY COLUMN `status` ENUM('DRAFT', 'Approved ', 'PROCESSING', 'FULFILLED', 'CANCELLED', 'ORDERED', 'COMPLETED', 'PO_CREATED', 'PARTIALLY_RELEASED', 'PARTIAL_STOCK_AVAILABLE') NULL DEFAULT 'DRAFT';
