ALTER TABLE material_request_items 
ADD COLUMN length DECIMAL(12, 4) DEFAULT 0,
ADD COLUMN width DECIMAL(12, 4) DEFAULT 0,
ADD COLUMN thickness DECIMAL(12, 4) DEFAULT 0,
ADD COLUMN diameter DECIMAL(12, 4) DEFAULT 0,
ADD COLUMN outer_diameter DECIMAL(12, 4) DEFAULT 0,
ADD COLUMN density DECIMAL(12, 8) DEFAULT 0,
ADD COLUMN weight_per_unit DECIMAL(12, 4) DEFAULT 0;
